//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.School.Portal.COMMONWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatGeneralesBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Common")]
    [System.SerializableAttribute()]
    public partial class CatGeneralesBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psACTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psDESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psFILTROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psIDCATALOGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psIDCATGENERALESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psIDSUBCATALOGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psNOMBRECATALOGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psVALORFILTROField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psACTIVO {
            get {
                return this.psACTIVOField;
            }
            set {
                if ((object.ReferenceEquals(this.psACTIVOField, value) != true)) {
                    this.psACTIVOField = value;
                    this.RaisePropertyChanged("psACTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psDESCRIPCION {
            get {
                return this.psDESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.psDESCRIPCIONField, value) != true)) {
                    this.psDESCRIPCIONField = value;
                    this.RaisePropertyChanged("psDESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psFILTRO {
            get {
                return this.psFILTROField;
            }
            set {
                if ((object.ReferenceEquals(this.psFILTROField, value) != true)) {
                    this.psFILTROField = value;
                    this.RaisePropertyChanged("psFILTRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psIDCATALOGO {
            get {
                return this.psIDCATALOGOField;
            }
            set {
                if ((object.ReferenceEquals(this.psIDCATALOGOField, value) != true)) {
                    this.psIDCATALOGOField = value;
                    this.RaisePropertyChanged("psIDCATALOGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psIDCATGENERALES {
            get {
                return this.psIDCATGENERALESField;
            }
            set {
                if ((object.ReferenceEquals(this.psIDCATGENERALESField, value) != true)) {
                    this.psIDCATGENERALESField = value;
                    this.RaisePropertyChanged("psIDCATGENERALES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psIDSUBCATALOGO {
            get {
                return this.psIDSUBCATALOGOField;
            }
            set {
                if ((object.ReferenceEquals(this.psIDSUBCATALOGOField, value) != true)) {
                    this.psIDSUBCATALOGOField = value;
                    this.RaisePropertyChanged("psIDSUBCATALOGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psNOMBRECATALOGO {
            get {
                return this.psNOMBRECATALOGOField;
            }
            set {
                if ((object.ReferenceEquals(this.psNOMBRECATALOGOField, value) != true)) {
                    this.psNOMBRECATALOGOField = value;
                    this.RaisePropertyChanged("psNOMBRECATALOGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psVALORFILTRO {
            get {
                return this.psVALORFILTROField;
            }
            set {
                if ((object.ReferenceEquals(this.psVALORFILTROField, value) != true)) {
                    this.psVALORFILTROField = value;
                    this.RaisePropertyChanged("psVALORFILTRO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaComunBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Common")]
    [System.SerializableAttribute()]
    public partial class RespuestaComunBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ThreeBits.School.Portal.COMMONWCF.ErrorBE itemErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE[] lstCatGeneralesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ThreeBits.School.Portal.COMMONWCF.CatalogosBE[] lstCatalogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE[] lstConfiguracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psDescripcionTablaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psIDCONFIGAPPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psIdentityTablaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThreeBits.School.Portal.COMMONWCF.ErrorBE itemError {
            get {
                return this.itemErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.itemErrorField, value) != true)) {
                    this.itemErrorField = value;
                    this.RaisePropertyChanged("itemError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE[] lstCatGenerales {
            get {
                return this.lstCatGeneralesField;
            }
            set {
                if ((object.ReferenceEquals(this.lstCatGeneralesField, value) != true)) {
                    this.lstCatGeneralesField = value;
                    this.RaisePropertyChanged("lstCatGenerales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThreeBits.School.Portal.COMMONWCF.CatalogosBE[] lstCatalogo {
            get {
                return this.lstCatalogoField;
            }
            set {
                if ((object.ReferenceEquals(this.lstCatalogoField, value) != true)) {
                    this.lstCatalogoField = value;
                    this.RaisePropertyChanged("lstCatalogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE[] lstConfiguracion {
            get {
                return this.lstConfiguracionField;
            }
            set {
                if ((object.ReferenceEquals(this.lstConfiguracionField, value) != true)) {
                    this.lstConfiguracionField = value;
                    this.RaisePropertyChanged("lstConfiguracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psDescripcionTabla {
            get {
                return this.psDescripcionTablaField;
            }
            set {
                if ((object.ReferenceEquals(this.psDescripcionTablaField, value) != true)) {
                    this.psDescripcionTablaField = value;
                    this.RaisePropertyChanged("psDescripcionTabla");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psIDCONFIGAPP {
            get {
                return this.psIDCONFIGAPPField;
            }
            set {
                if ((object.ReferenceEquals(this.psIDCONFIGAPPField, value) != true)) {
                    this.psIDCONFIGAPPField = value;
                    this.RaisePropertyChanged("psIDCONFIGAPP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psIdentityTabla {
            get {
                return this.psIdentityTablaField;
            }
            set {
                if ((object.ReferenceEquals(this.psIdentityTablaField, value) != true)) {
                    this.psIdentityTablaField = value;
                    this.RaisePropertyChanged("psIdentityTabla");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Common")]
    [System.SerializableAttribute()]
    public partial class ErrorBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool pbFlagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Text.StringBuilder psMensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool pbFlag {
            get {
                return this.pbFlagField;
            }
            set {
                if ((this.pbFlagField.Equals(value) != true)) {
                    this.pbFlagField = value;
                    this.RaisePropertyChanged("pbFlag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Text.StringBuilder psMensaje {
            get {
                return this.psMensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.psMensajeField, value) != true)) {
                    this.psMensajeField = value;
                    this.RaisePropertyChanged("psMensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CatalogosBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Common")]
    [System.SerializableAttribute()]
    public partial class CatalogosBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConfiguracionBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Common")]
    [System.SerializableAttribute()]
    public partial class ConfiguracionBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psACTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psDESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psIDCONFIGAPPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psIDCONFIGAPPNEWField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string psVALORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psACTIVO {
            get {
                return this.psACTIVOField;
            }
            set {
                if ((object.ReferenceEquals(this.psACTIVOField, value) != true)) {
                    this.psACTIVOField = value;
                    this.RaisePropertyChanged("psACTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psDESCRIPCION {
            get {
                return this.psDESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.psDESCRIPCIONField, value) != true)) {
                    this.psDESCRIPCIONField = value;
                    this.RaisePropertyChanged("psDESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psIDCONFIGAPP {
            get {
                return this.psIDCONFIGAPPField;
            }
            set {
                if ((object.ReferenceEquals(this.psIDCONFIGAPPField, value) != true)) {
                    this.psIDCONFIGAPPField = value;
                    this.RaisePropertyChanged("psIDCONFIGAPP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psIDCONFIGAPPNEW {
            get {
                return this.psIDCONFIGAPPNEWField;
            }
            set {
                if ((object.ReferenceEquals(this.psIDCONFIGAPPNEWField, value) != true)) {
                    this.psIDCONFIGAPPNEWField = value;
                    this.RaisePropertyChanged("psIDCONFIGAPPNEW");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string psVALOR {
            get {
                return this.psVALORField;
            }
            set {
                if ((object.ReferenceEquals(this.psVALORField, value) != true)) {
                    this.psVALORField = value;
                    this.RaisePropertyChanged("psVALOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="COMMONWCF.ICommonService")]
    public interface ICommonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetCatGenerales", ReplyAction="http://tempuri.org/ICommonService/GetCatGeneralesResponse")]
        ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE GetCatGenerales(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetCatGenerales", ReplyAction="http://tempuri.org/ICommonService/GetCatGeneralesResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> GetCatGeneralesAsync(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/AddCatGenerales", ReplyAction="http://tempuri.org/ICommonService/AddCatGeneralesResponse")]
        ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE AddCatGenerales(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/AddCatGenerales", ReplyAction="http://tempuri.org/ICommonService/AddCatGeneralesResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> AddCatGeneralesAsync(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetCatGenerales", ReplyAction="http://tempuri.org/ICommonService/SetCatGeneralesResponse")]
        ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE SetCatGenerales(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetCatGenerales", ReplyAction="http://tempuri.org/ICommonService/SetCatGeneralesResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> SetCatGeneralesAsync(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetCatEspecifico", ReplyAction="http://tempuri.org/ICommonService/GetCatEspecificoResponse")]
        ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE GetCatEspecifico(string sIdCatalogo, string sValorFiltro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetCatEspecifico", ReplyAction="http://tempuri.org/ICommonService/GetCatEspecificoResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> GetCatEspecificoAsync(string sIdCatalogo, string sValorFiltro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/AddCatEspecifico", ReplyAction="http://tempuri.org/ICommonService/AddCatEspecificoResponse")]
        ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE AddCatEspecifico(string sIdCatalogo, string sDescripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/AddCatEspecifico", ReplyAction="http://tempuri.org/ICommonService/AddCatEspecificoResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> AddCatEspecificoAsync(string sIdCatalogo, string sDescripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetConfigAPP", ReplyAction="http://tempuri.org/ICommonService/GetConfigAPPResponse")]
        ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE GetConfigAPP(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetConfigAPP", ReplyAction="http://tempuri.org/ICommonService/GetConfigAPPResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> GetConfigAPPAsync(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/AddConfigAPP", ReplyAction="http://tempuri.org/ICommonService/AddConfigAPPResponse")]
        ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE AddConfigAPP(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/AddConfigAPP", ReplyAction="http://tempuri.org/ICommonService/AddConfigAPPResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> AddConfigAPPAsync(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetConfigAPP", ReplyAction="http://tempuri.org/ICommonService/SetConfigAPPResponse")]
        ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE SetConfigAPP(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/SetConfigAPP", ReplyAction="http://tempuri.org/ICommonService/SetConfigAPPResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> SetConfigAPPAsync(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetDefinicionTabla", ReplyAction="http://tempuri.org/ICommonService/GetDefinicionTablaResponse")]
        ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE GetDefinicionTabla(string sNombreTabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICommonService/GetDefinicionTabla", ReplyAction="http://tempuri.org/ICommonService/GetDefinicionTablaResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> GetDefinicionTablaAsync(string sNombreTabla);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonServiceChannel : ThreeBits.School.Portal.COMMONWCF.ICommonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonServiceClient : System.ServiceModel.ClientBase<ThreeBits.School.Portal.COMMONWCF.ICommonService>, ThreeBits.School.Portal.COMMONWCF.ICommonService {
        
        public CommonServiceClient() {
        }
        
        public CommonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE GetCatGenerales(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item) {
            return base.Channel.GetCatGenerales(item);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> GetCatGeneralesAsync(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item) {
            return base.Channel.GetCatGeneralesAsync(item);
        }
        
        public ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE AddCatGenerales(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item) {
            return base.Channel.AddCatGenerales(item);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> AddCatGeneralesAsync(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item) {
            return base.Channel.AddCatGeneralesAsync(item);
        }
        
        public ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE SetCatGenerales(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item) {
            return base.Channel.SetCatGenerales(item);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> SetCatGeneralesAsync(ThreeBits.School.Portal.COMMONWCF.CatGeneralesBE item) {
            return base.Channel.SetCatGeneralesAsync(item);
        }
        
        public ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE GetCatEspecifico(string sIdCatalogo, string sValorFiltro) {
            return base.Channel.GetCatEspecifico(sIdCatalogo, sValorFiltro);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> GetCatEspecificoAsync(string sIdCatalogo, string sValorFiltro) {
            return base.Channel.GetCatEspecificoAsync(sIdCatalogo, sValorFiltro);
        }
        
        public ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE AddCatEspecifico(string sIdCatalogo, string sDescripcion) {
            return base.Channel.AddCatEspecifico(sIdCatalogo, sDescripcion);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> AddCatEspecificoAsync(string sIdCatalogo, string sDescripcion) {
            return base.Channel.AddCatEspecificoAsync(sIdCatalogo, sDescripcion);
        }
        
        public ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE GetConfigAPP(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item) {
            return base.Channel.GetConfigAPP(item);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> GetConfigAPPAsync(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item) {
            return base.Channel.GetConfigAPPAsync(item);
        }
        
        public ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE AddConfigAPP(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item) {
            return base.Channel.AddConfigAPP(item);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> AddConfigAPPAsync(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item) {
            return base.Channel.AddConfigAPPAsync(item);
        }
        
        public ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE SetConfigAPP(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item) {
            return base.Channel.SetConfigAPP(item);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> SetConfigAPPAsync(ThreeBits.School.Portal.COMMONWCF.ConfiguracionBE item) {
            return base.Channel.SetConfigAPPAsync(item);
        }
        
        public ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE GetDefinicionTabla(string sNombreTabla) {
            return base.Channel.GetDefinicionTabla(sNombreTabla);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.COMMONWCF.RespuestaComunBE> GetDefinicionTablaAsync(string sNombreTabla) {
            return base.Channel.GetDefinicionTablaAsync(sNombreTabla);
        }
    }
}
