//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNOS
    {
        public int IDALUMNO { get; set; }
        public string NUMEROMATRICULA { get; set; }
        public System.DateTime FECHAREGISTRO { get; set; }
        public System.DateTime FECHAMATRICULA { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public string NOMBRES { get; set; }
        public System.DateTime FECHANACIMIENTO { get; set; }
        public string SEXO { get; set; }
        public string NACIONALIDAD { get; set; }
        public string GRADO { get; set; }
        public string GRUPO { get; set; }
        public string NUMEROLISTA { get; set; }
        public string ESCUELAPROCEDENCIA { get; set; }
        public Nullable<int> HERMANOS { get; set; }
        public string GRADOHERMANOS { get; set; }
        public string CALLE { get; set; }
        public string NUMERO { get; set; }
        public string COLONIA { get; set; }
        public string DELEGACION { get; set; }
        public string ESTADO { get; set; }
        public string CODIGOPOSTAL { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string CURP { get; set; }
        public string EDADANOS { get; set; }
        public string EDADMESES { get; set; }
        public string TUTOR { get; set; }
        public string USUARIOALTA { get; set; }
        public string USUARIOMODIFICA { get; set; }
        public System.DateTime FECHAALTA { get; set; }
        public System.DateTime FECHAMODIFICA { get; set; }
        public string FOTO { get; set; }
        public string NIVELACADEMICO { get; set; }
        public string ESTATUS { get; set; }
        public string SERVERPATH { get; set; }
        public Nullable<int> BECA { get; set; }
        public Nullable<int> IDCICLO { get; set; }
        public Nullable<int> FORMAPAGO { get; set; }
    }
}
