//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUDIT_USUARIOS
    {
        public long IDUSUARIOAUDIT { get; set; }
        public Nullable<int> IDOPERACIONAUDIT { get; set; }
        public Nullable<long> IDUSUARIO { get; set; }
        public Nullable<long> IDAPLICACION { get; set; }
        public string IDSEXO { get; set; }
        public string IDTIPOPERSONA { get; set; }
        public string IDESTADOCIVIL { get; set; }
        public string IDAREA { get; set; }
        public string IDTIPOUSUARIO { get; set; }
        public string IDUSUARIOAPP { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHANACCONST { get; set; }
        public string USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public string RUTAFOTOPERFIL { get; set; }
        public Nullable<System.DateTime> FECHAALTA { get; set; }
        public Nullable<bool> ACTIVOUSR { get; set; }
        public Nullable<long> IDUSERMODIFICA { get; set; }
        public Nullable<long> IDAPPMODIFICA { get; set; }
        public Nullable<System.DateTime> FECHATRANSACCION { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual APLICACION APLICACION { get; set; }
        public virtual CAT_OPERACIONAUDIT CAT_OPERACIONAUDIT { get; set; }
    }
}
