//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CICLO
    {
        public int ID { get; set; }
        public string NOMBRECICLO { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHAFIN { get; set; }
        public Nullable<decimal> MONTOINSCRIPCION { get; set; }
        public Nullable<decimal> MONTOCOLEGIATURA { get; set; }
        public Nullable<int> ESTATUS { get; set; }
    }
}
