//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public string ID_CLIENTE { get; set; }
        public string RFCRECEP { get; set; }
        public string NMBRECEP { get; set; }
        public string CALLER { get; set; }
        public string NROEXTR { get; set; }
        public string NROINTR { get; set; }
        public string COLONIAR { get; set; }
        public string MUNICIPIOR { get; set; }
        public string LOCALIDADR { get; set; }
        public string ESTADOR { get; set; }
        public string PAISRECEP { get; set; }
        public string CPRECEP { get; set; }
    }
}
