//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colonias
    {
        public string ClaveColonia { get; set; }
        public string ClaveMunicipio { get; set; }
        public string ClaveEntidad { get; set; }
        public string NombreColonia { get; set; }
        public string CodigoPostal { get; set; }
        public string CodigoPostalAdministracion { get; set; }
        public string ClaveTipoAsentamiento { get; set; }
        public string TipoAsentamiento { get; set; }
        public string ClaveCiudad { get; set; }
        public string NombreCiudad { get; set; }
        public string Zona { get; set; }
        public string Universe { get; set; }
        public string Oracle { get; set; }
        public string MunOracle { get; set; }
        public string MunUniverse { get; set; }
    }
}
