//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTACTO
    {
        public long IDCONTACTO { get; set; }
        public Nullable<long> IDUSUARIO { get; set; }
        public Nullable<int> IDTIPOCONTACTO { get; set; }
        public string VALOR { get; set; }
        public Nullable<System.DateTime> FECHAALTA { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual CAT_TIPOCONTACTO CAT_TIPOCONTACTO { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
