//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESAS
    {
        public string ID_EMPRESA { get; set; }
        public string RFCEMISOR { get; set; }
        public string NMBEMISOR { get; set; }
        public string CALLEE { get; set; }
        public string NROEXTE { get; set; }
        public string NROINTE { get; set; }
        public string COLONIAE { get; set; }
        public string MUNICIPIOE { get; set; }
        public string LOCALIDADE { get; set; }
        public string ESTADOE { get; set; }
        public string PAISEMISOR { get; set; }
        public string CPEMISOR { get; set; }
        public string NMBREGIMEN { get; set; }
    }
}
