//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTACIONESXAPP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage('Microsoft.Usage', 'CA2214:DoNotCallOverridableMethodsInConstructors')]
        public ESTACIONESXAPP()
        {
            this.ROLESXUSUARIO = new HashSet<ROLESXUSUARIO>();
        }
    
        public long IDESTACIONXAPP { get; set; }
        public Nullable<long> IDAPLICACION { get; set; }
        public Nullable<int> IDESTACION { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual APLICACION APLICACION { get; set; }
        public virtual CAT_ESTACIONES CAT_ESTACIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage('Microsoft.Usage', 'CA2227:CollectionPropertiesShouldBeReadOnly')]
        public virtual ICollection<ROLESXUSUARIO> ROLESXUSUARIO { get; set; }
    }
}
