//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRUPO
    {
        public int IDGRUPO { get; set; }
        public Nullable<int> IDNIVEL { get; set; }
        public string IDGRADO { get; set; }
        public Nullable<int> IDCICLO { get; set; }
        public string NOMBREGRUPO { get; set; }
    }
}
