//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFOALUMNOS
    {
        public string NUMEROMATRICULA { get; set; }
        public string NOMBREPADRETUTOR { get; set; }
        public string OCUPACIONPADRE { get; set; }
        public string TELEFONOPADRE { get; set; }
        public string TELEFONOTRABAJOPADRE { get; set; }
        public string CELULARPADRE { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTOPADRE { get; set; }
        public string SUELDOPADRE { get; set; }
        public string NACIONALIDADPADRE { get; set; }
        public string NOMBREMADRETUTOR { get; set; }
        public string OCUPACIONMADRE { get; set; }
        public string TELEFONOMADRE { get; set; }
        public string TELEFONOTRABAJOMADRE { get; set; }
        public string CELULARMADRE { get; set; }
        public Nullable<System.DateTime> FECHANACIMIENTOMADRE { get; set; }
        public string SUELDOMADRE { get; set; }
        public string NACIONALIDADMADRE { get; set; }
        public string NOMBREFAMVECINO { get; set; }
        public string TELEFONOVECINO { get; set; }
        public string TELEFONOTRABAJOVECINO { get; set; }
        public string CELULARVECINO { get; set; }
        public Nullable<int> EDUCACIONFISICA { get; set; }
        public Nullable<int> MEDICAMENTO { get; set; }
        public string NOMBREMEDICAMENTO { get; set; }
        public string DOSISMEDICAMENTO { get; set; }
        public string ALIMENTOPROHIBIDO { get; set; }
        public string PESO { get; set; }
        public string TALLA { get; set; }
        public string TIPOSANGRE { get; set; }
        public Nullable<int> ENFERMEDADES { get; set; }
        public string NOMBREENFERMEDADES { get; set; }
        public string PROCEDIMIENTOCRISIS { get; set; }
        public Nullable<int> CERTIFICADO { get; set; }
        public Nullable<int> ENFERMEDADCERTIFICADO { get; set; }
        public Nullable<int> ALERGIA { get; set; }
        public string NOMBREALERGIA { get; set; }
        public string PROCEDIMINTOCRISISALERGIA { get; set; }
        public string NOMBREACCIDENTE { get; set; }
        public string TELEFONOACCIDENTE { get; set; }
        public string NOMBREHOSPITAL { get; set; }
        public Nullable<int> MEDICO { get; set; }
        public string NOMBREMEDICO { get; set; }
        public string TELEFONOMEDICO { get; set; }
        public string CEDULAMEDICO { get; set; }
        public Nullable<int> AUTORIZATRASLADO { get; set; }
        public string PROCEDIMIENTOACCIDENTE { get; set; }
    }
}
