//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGERROR
    {
        public long IDLOGERROR { get; set; }
        public Nullable<long> IDAPLICACION { get; set; }
        public string VCHMENSAJE { get; set; }
        public string VCHHOSTNAME { get; set; }
        public string VCHIP { get; set; }
        public string VCHSTACKTRACE { get; set; }
        public Nullable<System.DateTime> DTFECHAERROR { get; set; }
        public string VCHUSUARIO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual APLICACION APLICACION { get; set; }
    }
}
