//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class NUMERACIONES
    {
        public string CLAVE_PROCESO { get; set; }
        public string TIPO_PROC { get; set; }
        public decimal INICIAL { get; set; }
        public decimal FINAL { get; set; }
        public Nullable<decimal> ACTUAL { get; set; }
        public Nullable<System.DateTime> FECHA_INICIO { get; set; }
        public string SERIE { get; set; }
    }
}
