//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOSALUMNO
    {
        public int ID { get; set; }
        public Nullable<int> IDCICLO { get; set; }
        public string NUMEROMATRICULA { get; set; }
        public string IDGRUPO { get; set; }
        public string IDGRADO { get; set; }
        public Nullable<int> IDALUMNO { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<decimal> MONTOTOTAL { get; set; }
        public Nullable<decimal> MONTOACTUAL { get; set; }
        public Nullable<int> IDESTATUS { get; set; }
        public Nullable<System.DateTime> FECHAMOVIMIENTO { get; set; }
        public Nullable<System.DateTime> FECHAALTA { get; set; }
        public string USUARIOMODIFICA { get; set; }
        public string USUARIOALTA { get; set; }
        public Nullable<System.DateTime> FECHAMODIFICA { get; set; }
        public Nullable<int> MEDIOPAGO { get; set; }
        public string REFERENCIA { get; set; }
    }
}
