//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISOSXMENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage('Microsoft.Usage', 'CA2214:DoNotCallOverridableMethodsInConstructors')]
        public PERMISOSXMENU()
        {
            this.PERMISOSXSUBMENU = new HashSet<PERMISOSXSUBMENU>();
        }
    
        public long IDPERMISOSMENU { get; set; }
        public Nullable<long> IDROL { get; set; }
        public string NOMBREMENU { get; set; }
        public string TIPOOBJETO { get; set; }
        public string URL { get; set; }
        public string IMAGEN { get; set; }
        public Nullable<int> ORDEN { get; set; }
        public string TOOLTIP { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage('Microsoft.Usage', 'CA2227:CollectionPropertiesShouldBeReadOnly')]
        public virtual ICollection<PERMISOSXSUBMENU> PERMISOSXSUBMENU { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
