//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISOSXELEMENTOSOBJETO
    {
        public long IDELEMENTOSXOBJ { get; set; }
        public Nullable<long> IDPERMISOSOBJ { get; set; }
        public string ELEMENTO { get; set; }
        public string TOOLTIP { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual PERMISOXOBJETOS PERMISOXOBJETOS { get; set; }
    }
}
