//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POST()
        {
            this.COMENTARIO = new HashSet<COMENTARIO>();
            this.CATEGORIA = new HashSet<CATEGORIA>();
        }
    
        public int POSTID { get; set; }
        public string TITULO { get; set; }
        public string POSTEADOPOR { get; set; }
        public string DESCRIPCION { get; set; }
        public string CONTENIDO { get; set; }
        public System.DateTime FECHA { get; set; }
        public bool PUBLICADO { get; set; }
        public int COMENTARIOS { get; set; }
        public string IMAGEN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMENTARIO> COMENTARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORIA> CATEGORIA { get; set; }
    }
}
