//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTOS()
        {
            this.VENTA_DETALLE = new HashSet<VENTA_DETALLE>();
            this.VENTA_DETALLE_TMP = new HashSet<VENTA_DETALLE_TMP>();
        }
    
        public string ID_PRODUCTO { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<short> ID_UNIDAD_MEDIDA { get; set; }
        public Nullable<double> P_COMPRA { get; set; }
        public Nullable<double> P_VENTA { get; set; }
        public Nullable<double> EXISTENCIA { get; set; }
    
        public virtual UNIDAD_MEDIDA UNIDAD_MEDIDA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA_DETALLE> VENTA_DETALLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA_DETALLE_TMP> VENTA_DETALLE_TMP { get; set; }
    }
}
