//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLESXUSUARIO
    {
        public long IDROLXUSUARIO { get; set; }
        public Nullable<long> IDROL { get; set; }
        public Nullable<long> IDUSUARIO { get; set; }
        public Nullable<long> IDESTACIONXAPP { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual ESTACIONESXAPP ESTACIONESXAPP { get; set; }
        public virtual ROLES ROLES { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
