//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_USERSTATUS
    {
        public long ID { get; set; }
        public string USERID { get; set; }
        public string USERNAME { get; set; }
        public short STATUS { get; set; }
        public string THEME { get; set; }
        public Nullable<bool> SOUND { get; set; }
        public string AVATAR { get; set; }
        public string PROFILELINK { get; set; }
        public Nullable<System.DateTime> LASTLOGIN { get; set; }
        public Nullable<System.DateTime> LASTACTIVITY { get; set; }
    }
}
