//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CHATMESSAGES
    {
        public long ID { get; set; }
        public string CHATID { get; set; }
        public string SENDERNAME { get; set; }
        public string SENDERID { get; set; }
        public string RECIPIENTID { get; set; }
        public string RECIPIENTNAME { get; set; }
        public string MESSAGEBODY { get; set; }
        public bool ISTYPING { get; set; }
        public System.DateTime MESSAGETIME { get; set; }
        public bool ISREAD { get; set; }
    }
}
