//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACCIONES
    {
        public int ID { get; set; }
        public Nullable<int> IDALUMNO { get; set; }
        public Nullable<int> IDPAGO { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<System.DateTime> FECHATRANSACCION { get; set; }
        public string USUARIOTRANSACCION { get; set; }
        public string FORMAPAGO { get; set; }
        public string REFERENCIA { get; set; }
    }
}
