//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.CONTACTO = new HashSet<CONTACTO>();
            this.DOMICILIO = new HashSet<DOMICILIO>();
            this.ROLESXUSUARIO = new HashSet<ROLESXUSUARIO>();
            this.USUARIOXAPLICACION = new HashSet<USUARIOXAPLICACION>();
        }
    
        public long IDUSUARIO { get; set; }
        public Nullable<int> IDSEXO { get; set; }
        public Nullable<int> IDTIPOPERSONA { get; set; }
        public Nullable<int> IDESTADOCIVIL { get; set; }
        public Nullable<int> IDAREA { get; set; }
        public Nullable<int> IDTIPOUSUARIO { get; set; }
        public string IDUSUARIOAPP { get; set; }
        public string APATERNO { get; set; }
        public string AMATERNO { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<System.DateTime> FECHANACCONST { get; set; }
        public string USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public string RUTAFOTOPERFIL { get; set; }
        public Nullable<System.DateTime> FECHAALTA { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual CAT_AREA CAT_AREA { get; set; }
        public virtual CAT_ESTADOCIVIL CAT_ESTADOCIVIL { get; set; }
        public virtual CAT_SEXO CAT_SEXO { get; set; }
        public virtual CAT_TIPOPERSONA CAT_TIPOPERSONA { get; set; }
        public virtual CAT_TIPOUSUARIO CAT_TIPOUSUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTACTO> CONTACTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOMICILIO> DOMICILIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROLESXUSUARIO> ROLESXUSUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIOXAPLICACION> USUARIOXAPLICACION { get; set; }
    }
}
