//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTA()
        {
            this.VENTA_DETALLE = new HashSet<VENTA_DETALLE>();
        }
    
        public int ID_VENTA { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
        public string USER_LOGIN { get; set; }
        public string DOCSERIE { get; set; }
        public long DOCNUMBER { get; set; }
        public string DOCDATE { get; set; }
        public string TPODOC { get; set; }
        public string RFCEMISOR { get; set; }
        public string NMBEMISOR { get; set; }
        public string RFCRECEP { get; set; }
        public string NMBRECEP { get; set; }
        public string MONEDA { get; set; }
        public double SUBTOTAL { get; set; }
        public double IVA { get; set; }
        public double TOTAL { get; set; }
        public string COMENTARIOS { get; set; }
        public string VALORPALABRAS { get; set; }
        public string METODO { get; set; }
        public string CTAPAGO { get; set; }
        public string LUGAREXP { get; set; }
        public double TPOCAMBIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VENTA_DETALLE> VENTA_DETALLE { get; set; }
    }
}
