//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTA_DETALLE_TMP
    {
        public int ID_VENTA_DETALLE_TMP { get; set; }
        public string ID_PRODUCTO { get; set; }
        public double CANTIDAD { get; set; }
        public string USER_LOGIN { get; set; }
        public double P_VENTA { get; set; }
        public string ADUANA { get; set; }
        public string PEDIMENTO { get; set; }
        public string F_PEDIMENTO { get; set; }
        public string PREDIAL { get; set; }
    
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
