//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCFMETODOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage('Microsoft.Usage', 'CA2214:DoNotCallOverridableMethodsInConstructors')]
        public WCFMETODOS()
        {
            this.WCFRECURRENCIA = new HashSet<WCFRECURRENCIA>();
        }
    
        public long IDMETODOS { get; set; }
        public Nullable<long> IDAPLICACION { get; set; }
        public Nullable<long> IDSERVICIOS { get; set; }
        public string NOMBREMETODO { get; set; }
        public Nullable<bool> RECURRENTE { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual APLICACION APLICACION { get; set; }
        public virtual WCFSERVICIOS WCFSERVICIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage('Microsoft.Usage', 'CA2227:CollectionPropertiesShouldBeReadOnly')]
        public virtual ICollection<WCFRECURRENCIA> WCFRECURRENCIA { get; set; }
    }
}
