//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.Data.Models.Seguridad
{
    using System;
    using System.Collections.Generic;
    
    public partial class WCFRECURRENCIA
    {
        public long IDRECURRENCIA { get; set; }
        public Nullable<long> IDMETODOS { get; set; }
        public Nullable<System.DateTime> FECHAACCESO { get; set; }
        public Nullable<bool> ACTIVO { get; set; }
    
        public virtual WCFMETODOS WCFMETODOS { get; set; }
    }
}
