//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreeBits.School.Portal.SECURITYWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecutityDC", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.WCFService")]
    [System.SerializableAttribute()]
    public partial class SecutityDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.AplicacionBE> AplicacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.PermisoXElementosObjBE> ElementosObjetosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ThreeBits.School.Portal.SECURITYWCF.EncryptionBE EncriptacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.WCFMetodosBE> MetodosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.PermisosXObjetosBE> PermisoXObjetosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.PermisosXMenuBE> PermisosXMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.PermisoXSubmenuBE> PermisosXSubmenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ThreeBits.School.Portal.SECURITYWCF.RespuestaGralBE ResGralField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.AplicacionBE> Aplicaciones {
            get {
                return this.AplicacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.AplicacionesField, value) != true)) {
                    this.AplicacionesField = value;
                    this.RaisePropertyChanged("Aplicaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.PermisoXElementosObjBE> ElementosObjetos {
            get {
                return this.ElementosObjetosField;
            }
            set {
                if ((object.ReferenceEquals(this.ElementosObjetosField, value) != true)) {
                    this.ElementosObjetosField = value;
                    this.RaisePropertyChanged("ElementosObjetos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThreeBits.School.Portal.SECURITYWCF.EncryptionBE Encriptacion {
            get {
                return this.EncriptacionField;
            }
            set {
                if ((object.ReferenceEquals(this.EncriptacionField, value) != true)) {
                    this.EncriptacionField = value;
                    this.RaisePropertyChanged("Encriptacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.WCFMetodosBE> Metodos {
            get {
                return this.MetodosField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodosField, value) != true)) {
                    this.MetodosField = value;
                    this.RaisePropertyChanged("Metodos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.PermisosXObjetosBE> PermisoXObjetos {
            get {
                return this.PermisoXObjetosField;
            }
            set {
                if ((object.ReferenceEquals(this.PermisoXObjetosField, value) != true)) {
                    this.PermisoXObjetosField = value;
                    this.RaisePropertyChanged("PermisoXObjetos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.PermisosXMenuBE> PermisosXMenu {
            get {
                return this.PermisosXMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.PermisosXMenuField, value) != true)) {
                    this.PermisosXMenuField = value;
                    this.RaisePropertyChanged("PermisosXMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.PermisoXSubmenuBE> PermisosXSubmenu {
            get {
                return this.PermisosXSubmenuField;
            }
            set {
                if ((object.ReferenceEquals(this.PermisosXSubmenuField, value) != true)) {
                    this.PermisosXSubmenuField = value;
                    this.RaisePropertyChanged("PermisosXSubmenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ThreeBits.School.Portal.SECURITYWCF.RespuestaGralBE ResGral {
            get {
                return this.ResGralField;
            }
            set {
                if ((object.ReferenceEquals(this.ResGralField, value) != true)) {
                    this.ResGralField = value;
                    this.RaisePropertyChanged("ResGral");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EncryptionBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Security")]
    [System.SerializableAttribute()]
    public partial class EncryptionBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALORINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALOROUTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALORIN {
            get {
                return this.VALORINField;
            }
            set {
                if ((object.ReferenceEquals(this.VALORINField, value) != true)) {
                    this.VALORINField = value;
                    this.RaisePropertyChanged("VALORIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALOROUT {
            get {
                return this.VALOROUTField;
            }
            set {
                if ((object.ReferenceEquals(this.VALOROUTField, value) != true)) {
                    this.VALOROUTField = value;
                    this.RaisePropertyChanged("VALOROUT");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaGralBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Common")]
    [System.SerializableAttribute()]
    public partial class RespuestaGralBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ERRORMESSAGEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FLAGField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TRACEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ERRORMESSAGE {
            get {
                return this.ERRORMESSAGEField;
            }
            set {
                if ((object.ReferenceEquals(this.ERRORMESSAGEField, value) != true)) {
                    this.ERRORMESSAGEField = value;
                    this.RaisePropertyChanged("ERRORMESSAGE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FLAG {
            get {
                return this.FLAGField;
            }
            set {
                if ((this.FLAGField.Equals(value) != true)) {
                    this.FLAGField = value;
                    this.RaisePropertyChanged("FLAG");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TRACE {
            get {
                return this.TRACEField;
            }
            set {
                if ((object.ReferenceEquals(this.TRACEField, value) != true)) {
                    this.TRACEField = value;
                    this.RaisePropertyChanged("TRACE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AplicacionBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Security")]
    [System.SerializableAttribute()]
    public partial class AplicacionBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ACTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDAPLICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDUSRSXAPPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDUSUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PASSWORDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLINICIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ACTIVO {
            get {
                return this.ACTIVOField;
            }
            set {
                if ((this.ACTIVOField.Equals(value) != true)) {
                    this.ACTIVOField = value;
                    this.RaisePropertyChanged("ACTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDAPLICACION {
            get {
                return this.IDAPLICACIONField;
            }
            set {
                if ((this.IDAPLICACIONField.Equals(value) != true)) {
                    this.IDAPLICACIONField = value;
                    this.RaisePropertyChanged("IDAPLICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDUSRSXAPP {
            get {
                return this.IDUSRSXAPPField;
            }
            set {
                if ((this.IDUSRSXAPPField.Equals(value) != true)) {
                    this.IDUSRSXAPPField = value;
                    this.RaisePropertyChanged("IDUSRSXAPP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDUSUARIO {
            get {
                return this.IDUSUARIOField;
            }
            set {
                if ((this.IDUSUARIOField.Equals(value) != true)) {
                    this.IDUSUARIOField = value;
                    this.RaisePropertyChanged("IDUSUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PASSWORD {
            get {
                return this.PASSWORDField;
            }
            set {
                if ((object.ReferenceEquals(this.PASSWORDField, value) != true)) {
                    this.PASSWORDField = value;
                    this.RaisePropertyChanged("PASSWORD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URLINICIO {
            get {
                return this.URLINICIOField;
            }
            set {
                if ((object.ReferenceEquals(this.URLINICIOField, value) != true)) {
                    this.URLINICIOField = value;
                    this.RaisePropertyChanged("URLINICIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermisoXElementosObjBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Security")]
    [System.SerializableAttribute()]
    public partial class PermisoXElementosObjBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ACTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ELEMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDELEMENTOSXOBJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDPERMISOSOBJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOOLTIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ACTIVO {
            get {
                return this.ACTIVOField;
            }
            set {
                if ((this.ACTIVOField.Equals(value) != true)) {
                    this.ACTIVOField = value;
                    this.RaisePropertyChanged("ACTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ELEMENTO {
            get {
                return this.ELEMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ELEMENTOField, value) != true)) {
                    this.ELEMENTOField = value;
                    this.RaisePropertyChanged("ELEMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDELEMENTOSXOBJ {
            get {
                return this.IDELEMENTOSXOBJField;
            }
            set {
                if ((this.IDELEMENTOSXOBJField.Equals(value) != true)) {
                    this.IDELEMENTOSXOBJField = value;
                    this.RaisePropertyChanged("IDELEMENTOSXOBJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDPERMISOSOBJ {
            get {
                return this.IDPERMISOSOBJField;
            }
            set {
                if ((this.IDPERMISOSOBJField.Equals(value) != true)) {
                    this.IDPERMISOSOBJField = value;
                    this.RaisePropertyChanged("IDPERMISOSOBJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TOOLTIP {
            get {
                return this.TOOLTIPField;
            }
            set {
                if ((object.ReferenceEquals(this.TOOLTIPField, value) != true)) {
                    this.TOOLTIPField = value;
                    this.RaisePropertyChanged("TOOLTIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WCFMetodosBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Security")]
    [System.SerializableAttribute()]
    public partial class WCFMetodosBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ACTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActualizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDAPLICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDMETODOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDSERVICIOSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREMETODOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RECURRENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RowIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ACTIVO {
            get {
                return this.ACTIVOField;
            }
            set {
                if ((this.ACTIVOField.Equals(value) != true)) {
                    this.ACTIVOField = value;
                    this.RaisePropertyChanged("ACTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Actualizado {
            get {
                return this.ActualizadoField;
            }
            set {
                if ((this.ActualizadoField.Equals(value) != true)) {
                    this.ActualizadoField = value;
                    this.RaisePropertyChanged("Actualizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDAPLICACION {
            get {
                return this.IDAPLICACIONField;
            }
            set {
                if ((this.IDAPLICACIONField.Equals(value) != true)) {
                    this.IDAPLICACIONField = value;
                    this.RaisePropertyChanged("IDAPLICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDMETODOS {
            get {
                return this.IDMETODOSField;
            }
            set {
                if ((this.IDMETODOSField.Equals(value) != true)) {
                    this.IDMETODOSField = value;
                    this.RaisePropertyChanged("IDMETODOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDSERVICIOS {
            get {
                return this.IDSERVICIOSField;
            }
            set {
                if ((this.IDSERVICIOSField.Equals(value) != true)) {
                    this.IDSERVICIOSField = value;
                    this.RaisePropertyChanged("IDSERVICIOS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBREMETODO {
            get {
                return this.NOMBREMETODOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREMETODOField, value) != true)) {
                    this.NOMBREMETODOField = value;
                    this.RaisePropertyChanged("NOMBREMETODO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RECURRENTE {
            get {
                return this.RECURRENTEField;
            }
            set {
                if ((this.RECURRENTEField.Equals(value) != true)) {
                    this.RECURRENTEField = value;
                    this.RaisePropertyChanged("RECURRENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RowIndex {
            get {
                return this.RowIndexField;
            }
            set {
                if ((object.ReferenceEquals(this.RowIndexField, value) != true)) {
                    this.RowIndexField = value;
                    this.RaisePropertyChanged("RowIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermisosXObjetosBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Security")]
    [System.SerializableAttribute()]
    public partial class PermisosXObjetosBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ACTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDPERMISOSOBJField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREOBJETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAGINAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOOBJETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOOLTIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ACTIVO {
            get {
                return this.ACTIVOField;
            }
            set {
                if ((this.ACTIVOField.Equals(value) != true)) {
                    this.ACTIVOField = value;
                    this.RaisePropertyChanged("ACTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDPERMISOSOBJ {
            get {
                return this.IDPERMISOSOBJField;
            }
            set {
                if ((this.IDPERMISOSOBJField.Equals(value) != true)) {
                    this.IDPERMISOSOBJField = value;
                    this.RaisePropertyChanged("IDPERMISOSOBJ");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDROL {
            get {
                return this.IDROLField;
            }
            set {
                if ((this.IDROLField.Equals(value) != true)) {
                    this.IDROLField = value;
                    this.RaisePropertyChanged("IDROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBREOBJETO {
            get {
                return this.NOMBREOBJETOField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREOBJETOField, value) != true)) {
                    this.NOMBREOBJETOField = value;
                    this.RaisePropertyChanged("NOMBREOBJETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAGINA {
            get {
                return this.PAGINAField;
            }
            set {
                if ((object.ReferenceEquals(this.PAGINAField, value) != true)) {
                    this.PAGINAField = value;
                    this.RaisePropertyChanged("PAGINA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPOOBJETO {
            get {
                return this.TIPOOBJETOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOOBJETOField, value) != true)) {
                    this.TIPOOBJETOField = value;
                    this.RaisePropertyChanged("TIPOOBJETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TOOLTIP {
            get {
                return this.TOOLTIPField;
            }
            set {
                if ((object.ReferenceEquals(this.TOOLTIPField, value) != true)) {
                    this.TOOLTIPField = value;
                    this.RaisePropertyChanged("TOOLTIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermisosXMenuBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Security")]
    [System.SerializableAttribute()]
    public partial class PermisosXMenuBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ACTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDPERMISOSMENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDROLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMAGENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREMENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ORDENMENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOOBJETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOOLTIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ACTIVO {
            get {
                return this.ACTIVOField;
            }
            set {
                if ((this.ACTIVOField.Equals(value) != true)) {
                    this.ACTIVOField = value;
                    this.RaisePropertyChanged("ACTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDPERMISOSMENU {
            get {
                return this.IDPERMISOSMENUField;
            }
            set {
                if ((this.IDPERMISOSMENUField.Equals(value) != true)) {
                    this.IDPERMISOSMENUField = value;
                    this.RaisePropertyChanged("IDPERMISOSMENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDROL {
            get {
                return this.IDROLField;
            }
            set {
                if ((this.IDROLField.Equals(value) != true)) {
                    this.IDROLField = value;
                    this.RaisePropertyChanged("IDROL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAGEN {
            get {
                return this.IMAGENField;
            }
            set {
                if ((object.ReferenceEquals(this.IMAGENField, value) != true)) {
                    this.IMAGENField = value;
                    this.RaisePropertyChanged("IMAGEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBREMENU {
            get {
                return this.NOMBREMENUField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREMENUField, value) != true)) {
                    this.NOMBREMENUField = value;
                    this.RaisePropertyChanged("NOMBREMENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ORDENMENU {
            get {
                return this.ORDENMENUField;
            }
            set {
                if ((this.ORDENMENUField.Equals(value) != true)) {
                    this.ORDENMENUField = value;
                    this.RaisePropertyChanged("ORDENMENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPOOBJETO {
            get {
                return this.TIPOOBJETOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOOBJETOField, value) != true)) {
                    this.TIPOOBJETOField = value;
                    this.RaisePropertyChanged("TIPOOBJETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TOOLTIP {
            get {
                return this.TOOLTIPField;
            }
            set {
                if ((object.ReferenceEquals(this.TOOLTIPField, value) != true)) {
                    this.TOOLTIPField = value;
                    this.RaisePropertyChanged("TOOLTIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PermisoXSubmenuBE", Namespace="http://schemas.datacontract.org/2004/07/ThreeBits.Entities.Security")]
    [System.SerializableAttribute()]
    public partial class PermisoXSubmenuBE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ACTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDPERMISOSMENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDPERMISOSXSUBMENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IMAGENField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBRESUBMENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ORDENSUBMENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOOBJETOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOOLTIPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ACTIVO {
            get {
                return this.ACTIVOField;
            }
            set {
                if ((this.ACTIVOField.Equals(value) != true)) {
                    this.ACTIVOField = value;
                    this.RaisePropertyChanged("ACTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDPERMISOSMENU {
            get {
                return this.IDPERMISOSMENUField;
            }
            set {
                if ((this.IDPERMISOSMENUField.Equals(value) != true)) {
                    this.IDPERMISOSMENUField = value;
                    this.RaisePropertyChanged("IDPERMISOSMENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long IDPERMISOSXSUBMENU {
            get {
                return this.IDPERMISOSXSUBMENUField;
            }
            set {
                if ((this.IDPERMISOSXSUBMENUField.Equals(value) != true)) {
                    this.IDPERMISOSXSUBMENUField = value;
                    this.RaisePropertyChanged("IDPERMISOSXSUBMENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IMAGEN {
            get {
                return this.IMAGENField;
            }
            set {
                if ((object.ReferenceEquals(this.IMAGENField, value) != true)) {
                    this.IMAGENField = value;
                    this.RaisePropertyChanged("IMAGEN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRESUBMENU {
            get {
                return this.NOMBRESUBMENUField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBRESUBMENUField, value) != true)) {
                    this.NOMBRESUBMENUField = value;
                    this.RaisePropertyChanged("NOMBRESUBMENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ORDENSUBMENU {
            get {
                return this.ORDENSUBMENUField;
            }
            set {
                if ((this.ORDENSUBMENUField.Equals(value) != true)) {
                    this.ORDENSUBMENUField = value;
                    this.RaisePropertyChanged("ORDENSUBMENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPOOBJETO {
            get {
                return this.TIPOOBJETOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOOBJETOField, value) != true)) {
                    this.TIPOOBJETOField = value;
                    this.RaisePropertyChanged("TIPOOBJETO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TOOLTIP {
            get {
                return this.TOOLTIPField;
            }
            set {
                if ((object.ReferenceEquals(this.TOOLTIPField, value) != true)) {
                    this.TOOLTIPField = value;
                    this.RaisePropertyChanged("TOOLTIP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SECURITYWCF.ISecurityService")]
    public interface ISecurityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/checkPermisoXMethServ", ReplyAction="http://tempuri.org/ISecurityService/checkPermisoXMethServResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC checkPermisoXMethServ(string MethodName, string ServiceName, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/checkPermisoXMethServ", ReplyAction="http://tempuri.org/ISecurityService/checkPermisoXMethServResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> checkPermisoXMethServAsync(string MethodName, string ServiceName, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/checkMetodoXApp", ReplyAction="http://tempuri.org/ISecurityService/checkMetodoXAppResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC checkMetodoXApp(long IdApp, string sServiceName, string sMethodName, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/checkMetodoXApp", ReplyAction="http://tempuri.org/ISecurityService/checkMetodoXAppResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> checkMetodoXAppAsync(long IdApp, string sServiceName, string sMethodName, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getObjetosXAppRolPage", ReplyAction="http://tempuri.org/ISecurityService/getObjetosXAppRolPageResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC getObjetosXAppRolPage(long Rol, string Pagina, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getObjetosXAppRolPage", ReplyAction="http://tempuri.org/ISecurityService/getObjetosXAppRolPageResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getObjetosXAppRolPageAsync(long Rol, string Pagina, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getElementsObjectsXIdObj", ReplyAction="http://tempuri.org/ISecurityService/getElementsObjectsXIdObjResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC getElementsObjectsXIdObj(long IdPermisosXObj, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getElementsObjectsXIdObj", ReplyAction="http://tempuri.org/ISecurityService/getElementsObjectsXIdObjResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getElementsObjectsXIdObjAsync(long IdPermisosXObj, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getMenuXAppRol", ReplyAction="http://tempuri.org/ISecurityService/getMenuXAppRolResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC getMenuXAppRol(long Rol, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getMenuXAppRol", ReplyAction="http://tempuri.org/ISecurityService/getMenuXAppRolResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getMenuXAppRolAsync(long Rol, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getMenuXAppRolAdmin", ReplyAction="http://tempuri.org/ISecurityService/getMenuXAppRolAdminResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC getMenuXAppRolAdmin(long Rol, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getMenuXAppRolAdmin", ReplyAction="http://tempuri.org/ISecurityService/getMenuXAppRolAdminResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getMenuXAppRolAdminAsync(long Rol, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getMenuxRol", ReplyAction="http://tempuri.org/ISecurityService/getMenuxRolResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC getMenuxRol(long Rol, long AppRol, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getMenuxRol", ReplyAction="http://tempuri.org/ISecurityService/getMenuxRolResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getMenuxRolAsync(long Rol, long AppRol, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getMenuxRolAdmin", ReplyAction="http://tempuri.org/ISecurityService/getMenuxRolAdminResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC getMenuxRolAdmin(long Rol, long AppRol, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getMenuxRolAdmin", ReplyAction="http://tempuri.org/ISecurityService/getMenuxRolAdminResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getMenuxRolAdminAsync(long Rol, long AppRol, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getSubMenuXIdMenu", ReplyAction="http://tempuri.org/ISecurityService/getSubMenuXIdMenuResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC getSubMenuXIdMenu(long IdPermisoMenu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getSubMenuXIdMenu", ReplyAction="http://tempuri.org/ISecurityService/getSubMenuXIdMenuResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getSubMenuXIdMenuAsync(long IdPermisoMenu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getSubMenuXIdMenuAdmin", ReplyAction="http://tempuri.org/ISecurityService/getSubMenuXIdMenuAdminResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC getSubMenuXIdMenuAdmin(long IdPermisoMenu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getSubMenuXIdMenuAdmin", ReplyAction="http://tempuri.org/ISecurityService/getSubMenuXIdMenuAdminResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getSubMenuXIdMenuAdminAsync(long IdPermisoMenu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/encryptDesEncrypt", ReplyAction="http://tempuri.org/ISecurityService/encryptDesEncryptResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC encryptDesEncrypt(string Valor, int Tipo, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/encryptDesEncrypt", ReplyAction="http://tempuri.org/ISecurityService/encryptDesEncryptResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> encryptDesEncryptAsync(string Valor, int Tipo, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getAplicaciones", ReplyAction="http://tempuri.org/ISecurityService/getAplicacionesResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC getAplicaciones(string idAplicacion, string txtBusqueda, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/getAplicaciones", ReplyAction="http://tempuri.org/ISecurityService/getAplicacionesResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getAplicacionesAsync(string idAplicacion, string txtBusqueda, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addAplicacion", ReplyAction="http://tempuri.org/ISecurityService/addAplicacionResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC addAplicacion(ThreeBits.School.Portal.SECURITYWCF.AplicacionBE Aplicacion, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addAplicacion", ReplyAction="http://tempuri.org/ISecurityService/addAplicacionResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addAplicacionAsync(ThreeBits.School.Portal.SECURITYWCF.AplicacionBE Aplicacion, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/delMenu", ReplyAction="http://tempuri.org/ISecurityService/delMenuResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC delMenu(long idMenu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/delMenu", ReplyAction="http://tempuri.org/ISecurityService/delMenuResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> delMenuAsync(long idMenu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/delSubMenu", ReplyAction="http://tempuri.org/ISecurityService/delSubMenuResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC delSubMenu(long idSubMenu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/delSubMenu", ReplyAction="http://tempuri.org/ISecurityService/delSubMenuResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> delSubMenuAsync(long idSubMenu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/updAplicacion", ReplyAction="http://tempuri.org/ISecurityService/updAplicacionResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC updAplicacion(ThreeBits.School.Portal.SECURITYWCF.AplicacionBE Aplicacion, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/updAplicacion", ReplyAction="http://tempuri.org/ISecurityService/updAplicacionResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> updAplicacionAsync(ThreeBits.School.Portal.SECURITYWCF.AplicacionBE Aplicacion, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/updMenuxAppRol", ReplyAction="http://tempuri.org/ISecurityService/updMenuxAppRolResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC updMenuxAppRol(ThreeBits.School.Portal.SECURITYWCF.PermisosXMenuBE Menu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/updMenuxAppRol", ReplyAction="http://tempuri.org/ISecurityService/updMenuxAppRolResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> updMenuxAppRolAsync(ThreeBits.School.Portal.SECURITYWCF.PermisosXMenuBE Menu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/updSubMenuxAppRol", ReplyAction="http://tempuri.org/ISecurityService/updSubMenuxAppRolResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC updSubMenuxAppRol(ThreeBits.School.Portal.SECURITYWCF.PermisoXSubmenuBE SubMenu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/updSubMenuxAppRol", ReplyAction="http://tempuri.org/ISecurityService/updSubMenuxAppRolResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> updSubMenuxAppRolAsync(ThreeBits.School.Portal.SECURITYWCF.PermisoXSubmenuBE SubMenu, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addMetodo", ReplyAction="http://tempuri.org/ISecurityService/addMetodoResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC addMetodo(System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.WCFMetodosBE> Metodos, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addMetodo", ReplyAction="http://tempuri.org/ISecurityService/addMetodoResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addMetodoAsync(System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.WCFMetodosBE> Metodos, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addRolxApp", ReplyAction="http://tempuri.org/ISecurityService/addRolxAppResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC addRolxApp(string Rol, long AppRol, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addRolxApp", ReplyAction="http://tempuri.org/ISecurityService/addRolxAppResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addRolxAppAsync(string Rol, long AppRol, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addServicio", ReplyAction="http://tempuri.org/ISecurityService/addServicioResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC addServicio(string Servicio, long IdApp, bool Recurrente, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addServicio", ReplyAction="http://tempuri.org/ISecurityService/addServicioResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addServicioAsync(string Servicio, long IdApp, bool Recurrente, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addMenuxAppRol", ReplyAction="http://tempuri.org/ISecurityService/addMenuxAppRolResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC addMenuxAppRol(long Rol, long IdApp, string Menu, string Img, string Obj, string Url, string Tool, long Orden, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addMenuxAppRol", ReplyAction="http://tempuri.org/ISecurityService/addMenuxAppRolResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addMenuxAppRolAsync(long Rol, long IdApp, string Menu, string Img, string Obj, string Url, string Tool, long Orden, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addSubMenuxAppRol", ReplyAction="http://tempuri.org/ISecurityService/addSubMenuxAppRolResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC addSubMenuxAppRol(long IdSubMenu, string SubMenu, string Img, string Obj, string Url, string Tool, long Orden, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addSubMenuxAppRol", ReplyAction="http://tempuri.org/ISecurityService/addSubMenuxAppRolResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addSubMenuxAppRolAsync(long IdSubMenu, string SubMenu, string Img, string Obj, string Url, string Tool, long Orden, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addPermisosxObjeto", ReplyAction="http://tempuri.org/ISecurityService/addPermisosxObjetoResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC addPermisosxObjeto(long IdRol, string Pagina, string Obj, string TipoObj, string Tool, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addPermisosxObjeto", ReplyAction="http://tempuri.org/ISecurityService/addPermisosxObjetoResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addPermisosxObjetoAsync(long IdRol, string Pagina, string Obj, string TipoObj, string Tool, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addPermisosxElementoObjeto", ReplyAction="http://tempuri.org/ISecurityService/addPermisosxElementoObjetoResponse")]
        ThreeBits.School.Portal.SECURITYWCF.SecutityDC addPermisosxElementoObjeto(long IdPermiosObj, string Elemento, string Tool, long App, string PasswordApp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityService/addPermisosxElementoObjeto", ReplyAction="http://tempuri.org/ISecurityService/addPermisosxElementoObjetoResponse")]
        System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addPermisosxElementoObjetoAsync(long IdPermiosObj, string Elemento, string Tool, long App, string PasswordApp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityServiceChannel : ThreeBits.School.Portal.SECURITYWCF.ISecurityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityServiceClient : System.ServiceModel.ClientBase<ThreeBits.School.Portal.SECURITYWCF.ISecurityService>, ThreeBits.School.Portal.SECURITYWCF.ISecurityService {
        
        public SecurityServiceClient() {
        }
        
        public SecurityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC checkPermisoXMethServ(string MethodName, string ServiceName, long App, string PasswordApp) {
            return base.Channel.checkPermisoXMethServ(MethodName, ServiceName, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> checkPermisoXMethServAsync(string MethodName, string ServiceName, long App, string PasswordApp) {
            return base.Channel.checkPermisoXMethServAsync(MethodName, ServiceName, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC checkMetodoXApp(long IdApp, string sServiceName, string sMethodName, long App, string PasswordApp) {
            return base.Channel.checkMetodoXApp(IdApp, sServiceName, sMethodName, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> checkMetodoXAppAsync(long IdApp, string sServiceName, string sMethodName, long App, string PasswordApp) {
            return base.Channel.checkMetodoXAppAsync(IdApp, sServiceName, sMethodName, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC getObjetosXAppRolPage(long Rol, string Pagina, long App, string PasswordApp) {
            return base.Channel.getObjetosXAppRolPage(Rol, Pagina, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getObjetosXAppRolPageAsync(long Rol, string Pagina, long App, string PasswordApp) {
            return base.Channel.getObjetosXAppRolPageAsync(Rol, Pagina, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC getElementsObjectsXIdObj(long IdPermisosXObj, long App, string PasswordApp) {
            return base.Channel.getElementsObjectsXIdObj(IdPermisosXObj, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getElementsObjectsXIdObjAsync(long IdPermisosXObj, long App, string PasswordApp) {
            return base.Channel.getElementsObjectsXIdObjAsync(IdPermisosXObj, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC getMenuXAppRol(long Rol, long App, string PasswordApp) {
            return base.Channel.getMenuXAppRol(Rol, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getMenuXAppRolAsync(long Rol, long App, string PasswordApp) {
            return base.Channel.getMenuXAppRolAsync(Rol, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC getMenuXAppRolAdmin(long Rol, long App, string PasswordApp) {
            return base.Channel.getMenuXAppRolAdmin(Rol, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getMenuXAppRolAdminAsync(long Rol, long App, string PasswordApp) {
            return base.Channel.getMenuXAppRolAdminAsync(Rol, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC getMenuxRol(long Rol, long AppRol, long App, string PasswordApp) {
            return base.Channel.getMenuxRol(Rol, AppRol, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getMenuxRolAsync(long Rol, long AppRol, long App, string PasswordApp) {
            return base.Channel.getMenuxRolAsync(Rol, AppRol, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC getMenuxRolAdmin(long Rol, long AppRol, long App, string PasswordApp) {
            return base.Channel.getMenuxRolAdmin(Rol, AppRol, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getMenuxRolAdminAsync(long Rol, long AppRol, long App, string PasswordApp) {
            return base.Channel.getMenuxRolAdminAsync(Rol, AppRol, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC getSubMenuXIdMenu(long IdPermisoMenu, long App, string PasswordApp) {
            return base.Channel.getSubMenuXIdMenu(IdPermisoMenu, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getSubMenuXIdMenuAsync(long IdPermisoMenu, long App, string PasswordApp) {
            return base.Channel.getSubMenuXIdMenuAsync(IdPermisoMenu, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC getSubMenuXIdMenuAdmin(long IdPermisoMenu, long App, string PasswordApp) {
            return base.Channel.getSubMenuXIdMenuAdmin(IdPermisoMenu, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getSubMenuXIdMenuAdminAsync(long IdPermisoMenu, long App, string PasswordApp) {
            return base.Channel.getSubMenuXIdMenuAdminAsync(IdPermisoMenu, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC encryptDesEncrypt(string Valor, int Tipo, long App, string PasswordApp) {
            return base.Channel.encryptDesEncrypt(Valor, Tipo, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> encryptDesEncryptAsync(string Valor, int Tipo, long App, string PasswordApp) {
            return base.Channel.encryptDesEncryptAsync(Valor, Tipo, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC getAplicaciones(string idAplicacion, string txtBusqueda, long App, string PasswordApp) {
            return base.Channel.getAplicaciones(idAplicacion, txtBusqueda, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> getAplicacionesAsync(string idAplicacion, string txtBusqueda, long App, string PasswordApp) {
            return base.Channel.getAplicacionesAsync(idAplicacion, txtBusqueda, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC addAplicacion(ThreeBits.School.Portal.SECURITYWCF.AplicacionBE Aplicacion, long App, string PasswordApp) {
            return base.Channel.addAplicacion(Aplicacion, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addAplicacionAsync(ThreeBits.School.Portal.SECURITYWCF.AplicacionBE Aplicacion, long App, string PasswordApp) {
            return base.Channel.addAplicacionAsync(Aplicacion, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC delMenu(long idMenu, long App, string PasswordApp) {
            return base.Channel.delMenu(idMenu, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> delMenuAsync(long idMenu, long App, string PasswordApp) {
            return base.Channel.delMenuAsync(idMenu, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC delSubMenu(long idSubMenu, long App, string PasswordApp) {
            return base.Channel.delSubMenu(idSubMenu, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> delSubMenuAsync(long idSubMenu, long App, string PasswordApp) {
            return base.Channel.delSubMenuAsync(idSubMenu, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC updAplicacion(ThreeBits.School.Portal.SECURITYWCF.AplicacionBE Aplicacion, long App, string PasswordApp) {
            return base.Channel.updAplicacion(Aplicacion, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> updAplicacionAsync(ThreeBits.School.Portal.SECURITYWCF.AplicacionBE Aplicacion, long App, string PasswordApp) {
            return base.Channel.updAplicacionAsync(Aplicacion, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC updMenuxAppRol(ThreeBits.School.Portal.SECURITYWCF.PermisosXMenuBE Menu, long App, string PasswordApp) {
            return base.Channel.updMenuxAppRol(Menu, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> updMenuxAppRolAsync(ThreeBits.School.Portal.SECURITYWCF.PermisosXMenuBE Menu, long App, string PasswordApp) {
            return base.Channel.updMenuxAppRolAsync(Menu, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC updSubMenuxAppRol(ThreeBits.School.Portal.SECURITYWCF.PermisoXSubmenuBE SubMenu, long App, string PasswordApp) {
            return base.Channel.updSubMenuxAppRol(SubMenu, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> updSubMenuxAppRolAsync(ThreeBits.School.Portal.SECURITYWCF.PermisoXSubmenuBE SubMenu, long App, string PasswordApp) {
            return base.Channel.updSubMenuxAppRolAsync(SubMenu, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC addMetodo(System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.WCFMetodosBE> Metodos, long App, string PasswordApp) {
            return base.Channel.addMetodo(Metodos, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addMetodoAsync(System.Collections.Generic.List<ThreeBits.School.Portal.SECURITYWCF.WCFMetodosBE> Metodos, long App, string PasswordApp) {
            return base.Channel.addMetodoAsync(Metodos, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC addRolxApp(string Rol, long AppRol, long App, string PasswordApp) {
            return base.Channel.addRolxApp(Rol, AppRol, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addRolxAppAsync(string Rol, long AppRol, long App, string PasswordApp) {
            return base.Channel.addRolxAppAsync(Rol, AppRol, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC addServicio(string Servicio, long IdApp, bool Recurrente, long App, string PasswordApp) {
            return base.Channel.addServicio(Servicio, IdApp, Recurrente, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addServicioAsync(string Servicio, long IdApp, bool Recurrente, long App, string PasswordApp) {
            return base.Channel.addServicioAsync(Servicio, IdApp, Recurrente, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC addMenuxAppRol(long Rol, long IdApp, string Menu, string Img, string Obj, string Url, string Tool, long Orden, long App, string PasswordApp) {
            return base.Channel.addMenuxAppRol(Rol, IdApp, Menu, Img, Obj, Url, Tool, Orden, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addMenuxAppRolAsync(long Rol, long IdApp, string Menu, string Img, string Obj, string Url, string Tool, long Orden, long App, string PasswordApp) {
            return base.Channel.addMenuxAppRolAsync(Rol, IdApp, Menu, Img, Obj, Url, Tool, Orden, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC addSubMenuxAppRol(long IdSubMenu, string SubMenu, string Img, string Obj, string Url, string Tool, long Orden, long App, string PasswordApp) {
            return base.Channel.addSubMenuxAppRol(IdSubMenu, SubMenu, Img, Obj, Url, Tool, Orden, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addSubMenuxAppRolAsync(long IdSubMenu, string SubMenu, string Img, string Obj, string Url, string Tool, long Orden, long App, string PasswordApp) {
            return base.Channel.addSubMenuxAppRolAsync(IdSubMenu, SubMenu, Img, Obj, Url, Tool, Orden, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC addPermisosxObjeto(long IdRol, string Pagina, string Obj, string TipoObj, string Tool, long App, string PasswordApp) {
            return base.Channel.addPermisosxObjeto(IdRol, Pagina, Obj, TipoObj, Tool, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addPermisosxObjetoAsync(long IdRol, string Pagina, string Obj, string TipoObj, string Tool, long App, string PasswordApp) {
            return base.Channel.addPermisosxObjetoAsync(IdRol, Pagina, Obj, TipoObj, Tool, App, PasswordApp);
        }
        
        public ThreeBits.School.Portal.SECURITYWCF.SecutityDC addPermisosxElementoObjeto(long IdPermiosObj, string Elemento, string Tool, long App, string PasswordApp) {
            return base.Channel.addPermisosxElementoObjeto(IdPermiosObj, Elemento, Tool, App, PasswordApp);
        }
        
        public System.Threading.Tasks.Task<ThreeBits.School.Portal.SECURITYWCF.SecutityDC> addPermisosxElementoObjetoAsync(long IdPermiosObj, string Elemento, string Tool, long App, string PasswordApp) {
            return base.Channel.addPermisosxElementoObjetoAsync(IdPermiosObj, Elemento, Tool, App, PasswordApp);
        }
    }
}
